### ISSUE TITLE
Parsing owncloud logfile, EXPECTED EOF GOT {

### ISSUE THREAD

**Issue by freezed** [dominictarr/JSON.sh#44]
Hi, sorry if it's trivial or obvious, I'm new in JSON and shell script
I try to parse some ownCloud log file and I've got an _**EXPECTED EOF GOT {**_ error after the end of the first json line.

```
freezed@machine ~ # script/JSON.sh < oc-log.json
["reqId"]	"mwpZIyDDtQG3gZhKZODF"
["remoteAddr"]	"192.168.1.2"
["app"]	"caldav"
["message"]	"Exception: {\"Message\":\"HTTP\\\/1.1 404 Node with name 'calendar1_shared_by_user_4' could not be found\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(76): OCA\\\\DAV\\\\CalDAV\\\\CalendarHome->getChild('calendar1_shared_b...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(903): Sabre\\\\DAV\\\\Tree->getNodeForPath('calendars\\\/user_3...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(334): Sabre\\\\DAV\\\\Server->getPropertiesForPath('calendars\\\/user_3...', Array, 0)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/caldav.php(81): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/CalendarHome.php\",\"Line\":104,\"User\":\"user_3\"}"
["level"]	0
["time"]	"2016-08-10T04:18:21+00:00"
["method"]	"PROPFIND"
["url"]	"\/remote.php\/caldav\/calendars\/user_3\/calendar1_shared_by_user_4\/"
["user"]	"user_3"
[]	{"reqId":"mwpZIyDDtQG3gZhKZODF","remoteAddr":"192.168.1.2","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 Node with name 'calendar1_shared_by_user_4' could not be found\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(76): OCA\\\\DAV\\\\CalDAV\\\\CalendarHome->getChild('calendar1_shared_b...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(903): Sabre\\\\DAV\\\\Tree->getNodeForPath('calendars\\\/user_3...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(334): Sabre\\\\DAV\\\\Server->getPropertiesForPath('calendars\\\/user_3...', Array, 0)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/caldav.php(81): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/CalendarHome.php\",\"Line\":104,\"User\":\"user_3\"}","level":0,"time":"2016-08-10T04:18:21+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user_3\/calendar1_shared_by_user_4\/","user":"user_3"}
EXPECTED EOF GOT {
zsh: exit 1     script/JSON.sh < oc-log.json
```
You can found my sample log file **[here](https://gist.github.com/freezed/1bda40d994ac916f911a3fbde36796dc.js)**

**Comment by dominictarr** [comment]
it's saying that your json is invalid. It sounds like it's 2 json files concatenated (prehaps it's line delimited json?)  and so it read one json object correctly, and then expected to see the end of the file (EOF) but instead it saw the start of another json file.

**Comment by freezed** [comment]
Ok, I'll ask ownCloud people wich kind of tool they use for viewing the logs
