### ISSUE TITLE
Does Not Work on CircleCI

### ISSUE THREAD

**Issue by grndvl1** [dominictarr/JSON.sh#55]
Trying to use this with CircleCI scripts and the JSON file parses and blows up with this error

`SyntaxError: Unexpected token \ in JSON at position 35<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at parse (/home/node/data/node_modules/body-parser/lib/types/json.js:89:19)<br> &nbsp; &nbsp;at /home/node/data/node_modules/body-parser/lib/read.js:121:18<br> &nbsp; &nbsp;at invokeCallback (/home/node/data/node_modules/raw-body/index.js:224:16)<br> &nbsp; &nbsp;at done (/home/node/data/node_modules/raw-body/index.js:213:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/home/node/data/node_modules/raw-body/index.js:273:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:203:15)<br> &nbsp; &nbsp;at IncomingMessage.EventEmitter.emit (domain.js:466:23)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:1145:12)<br> &nbsp; &nbsp;at process._tickCallback (internal/process/next_tick.js:63:19)</pre>`

Also it does not work in windows shell same script different error at the call to the JSON parser

`DATA=$URL| ./scripts/JSON.sh | egrep '\["upload_url","[^"]*"\]'`

get this error

`EXPECTED value GOT EOF`

**Comment by grndvl1** [comment]
Looks like you have HTML code in your json which might be an issue...just spitballing here
